sudo: true
dist: xenial

language: cpp
compiler: clang

matrix:
  include:
    - addons:
        apt:
          update: true
          packages:
            - lua5.2
            - liblua5.2-dev
            - libssl-dev
            - ninja
            - openssl
            - zlib1g-dev
            - gperf
      env:
        - LUA_VERSION="Lua 5.2"
        - LUA="lua"
    - addons:
        apt:
          update: true
          packages:
            - lua5.3
            - liblua5.3-dev
            - libssl-dev
            - ninja
            - openssl
            - zlib1g-dev
            - gperf
      env:
        - LUA_VERSION="Lua 5.3"
        - LUA="lua5.3"

script:
- ./compile.sh
