sudo: true
dist: xenial

language: cpp
compiler: clang
addons:
  apt:
    update: true
    packages:
    - libssl-dev
    - ninja
    - openssl
    - zlib1g-dev
    - gperf
    - liblua5.2-dev
    - lua5.2

script:
- ./compile.sh
