sudo: true
dist: xenial

language: cpp
compiler: clang

matrix:
  include:
    - addons:
        apt:
          packages:
            - lua5.1
            - liblua5.1-dev
    - addons:
        apt:
          packages:
            - lua5.2
            - liblua5.2-dev
    - addons:
        apt:
          packages:
            - lua5.3
            - liblua5.3-dev

compiler: clang

addons:
  apt:
    update: true
    packages:
    - libssl-dev
    - ninja
    - openssl
    - zlib1g-dev
    - gperf
    - libopus-dev

script:
- ./compile.sh
